run:
  concurrency: 4
  timeout: 5m
  tests: true
  allow-parallel-runners: true
  go: '1.24'

linters:
  enable:
    - gosec
    - gci

issues:
  exclude-rules:

    - text: "weak random number generator"
      linters:
        - gosec

    # The BitTorrent protocol is based upon weak cryptographic primitives
    # it's pointless to be stubborn about their usage
    - text: "weak cryptographic primitive"
      linters:
        - gosec

    - text: "G115: integer overflow conversion"
      linters:
        - gosec
