run:
  concurrency: 4
  timeout: 5m
  tests: true
  allow-parallel-runners: true
  go: '1.23'

linters:
  enable:
    - gosec
    - gci

issues:
  new: true
  exclude-rules:

    - linters:
        - staticcheck
      text: "SA4027:"

    - linters:
        - staticcheck
      text: "ST1005:"

    - text: "weak random number generator"
      linters:
        - gosec

    - text: "weak cryptographic primitive"
      linters:
        - gosec

    - path: dht/mainline/routingTable.go
      text: "integer overflow conversion uint -> int"
      linters:
        - gosec

    - path: main.go
      text: "integer overflow conversion uint -> int"
      linters:
        - gosec
    
    - path: persistence/postgres.go
      text: "G115: integer overflow conversion int64 -> uint"
      linters:
        - gosec
