name: "Lint"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false

      - name: GoLang CI Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          only-new-issues: true
          skip-pkg-cache: true
          skip-build-cache: true
          args: --timeout=5m
